[package]
name = "secure_medical_data"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
openssl = { version = "0.10", features = ["vendored"] }
rand = "0.8"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
